CREATE TABLE estabelecimento
(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
	nome VARCHAR(250) NOT NULL,
	endereco VARCHAR(32672) NOT NULL,
	votos INT NOT NULL DEFAULT 0,
        PRIMARY KEY(id)
);

